# Generated by Django 6.0.4 on 2026-05-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_document_id_type_document_type_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
