# Generated by Django 6.0.4 on 2026-04-29 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0007_alter_demandebrevet_date_reception_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brevet',
            name='id',
        ),
        migrations.AddField(
            model_name='brevet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brevets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brevet',
            name='id_demande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brevets.demandebrevet'),
        ),
        migrations.AlterField(
            model_name='brevet',
            name='id_dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brevets.deposant'),
        ),
        migrations.AlterField(
            model_name='brevet',
            name='id_inv',
            field=models.ManyToManyField(related_name='brevets', to='brevets.inventeur'),
        ),
    ]
