# Generated by Django 6.0.4 on 2026-04-29 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0008_remove_brevet_id_brevet_user_alter_brevet_id_demande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevet',
            name='id_dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brevets.deposant'),
        ),
        migrations.AlterField(
            model_name='brevet',
            name='id_inv',
            field=models.ManyToManyField(blank=True, related_name='brevets', to='brevets.inventeur'),
        ),
        migrations.AlterField(
            model_name='deposant',
            name='adresse_dep',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deposant',
            name='denomination',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deposant',
            name='id_demande',
            field=models.ForeignKey(blank=True, db_column='id_demande', null=True, on_delete=django.db.models.deletion.CASCADE, to='brevets.demandebrevet'),
        ),
        migrations.AlterField(
            model_name='deposant',
            name='nationalite',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventeur',
            name='adress_inv',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventeur',
            name='id_demande',
            field=models.ManyToManyField(blank=True, related_name='inventeurs', to='brevets.demandebrevet'),
        ),
    ]
