# Generated by Django 6.0.4 on 2026-05-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0009_alter_brevet_id_dep_alter_brevet_id_inv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_abrege',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_cession',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_copie_int',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_dessins_dup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_dessins_orig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_memoire_fr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_memoire_fr_dup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_memoire_nat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_pouvoir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_priorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_titre',
            field=models.BooleanField(default=False),
        ),
    ]
