# Generated by Django 6.0.4 on 2026-05-04 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0010_demandebrevet_piece_abrege_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brevet',
            name='id_inv',
        ),
        migrations.AlterField(
            model_name='deposant',
            name='id_demande',
            field=models.ForeignKey(blank=True, db_column='id_demande', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposants', to='brevets.demandebrevet'),
        ),
        migrations.RemoveField(
            model_name='inventeur',
            name='id_demande',
        ),
        migrations.AddField(
            model_name='brevet',
            name='id_inv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brevets', to='brevets.inventeur'),
        ),
        migrations.AddField(
            model_name='inventeur',
            name='id_demande',
            field=models.ForeignKey(blank=True, db_column='id_demande', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventeurs', to='brevets.demandebrevet'),
        ),
    ]
