# Generated by Django 6.0.4 on 2026-05-04 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0011_remove_brevet_id_inv_alter_deposant_id_demande_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brevet',
            name='id_inv',
        ),
        migrations.AddField(
            model_name='inventeur',
            name='id_brevet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventeurs', to='brevets.brevet'),
        ),
    ]
